coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

# https://docs.codecov.com/docs/fixing-paths
# This is needed because:
#
fixes:
  - "/go/src/open-cluster-management.io/cluster-proxy/::"