coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

# https://docs.codecov.com/docs/fixing-paths
# This is needed because:
# The path on codecov is cluster-proxy/go/src/open-cluster-management.io/cluster-proxy/pkg/proxyserver/controllers/service_resolver_controller.go and it should fix to pkg/proxyserver/controllers/service_resolver_controller.go
fixes:
  - "go/src/open-cluster-management.io/cluster-proxy/::"

ignore:
  - "**/*generated*.go"

codecov:
  disable_default_path_fixes: true
